spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fitcha?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ssafy.fitcha.model.dto
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: VARCHAR

challenge:
  file:
    upload-dir: ./uploads/challenges

proof:
  file:
    upload-dir: ./uploads/proofs

user:
  file:
    upload-dir: ./uploads/users